--EX1
SELECT NAME
FROM STUDENTS
WHERE MARKS>75
ORDER BY RIGHT(NAME,3), ID

--EX2
SELECT USER_ID,
CONCAT(UPPER(LEFT(NAME,1)), LOWER(RIGHT(NAME, LENGTH(NAME)-1))) AS NAME
FROM USERS 
ORDER BY user_id

--EX3 
SELECT MANUFACTURER,
'$' || ROUND(SUM(TOTAL_SALES)/1000000,0) || ' ' || 'MILLION'
FROM pharmacy_sales
GROUP BY MANUFACTURER
ORDER BY SUM(TOTAL_SALES) DESC, MANUFACTURER

--EX4 
SELECT EXTRACT(MONTH FROM SUBMIT_DATE) AS MONTH_OF_YEAR, product_id, 
ROUND(AVG(STARS),2) AS AVG_STAR_RATING
FROM reviews
GROUP BY EXTRACT(MONTH FROM SUBMIT_DATE), product_id
ORDER BY EXTRACT(MONTH FROM SUBMIT_DATE), product_id

--EX5 
SELECT SENDER_ID,
COUNT(MESSAGE_ID) AS MESSAGE_COUNT
FROM messages
WHERE EXTRACT(MONTH FROM SENT_DATE) =8 
AND EXTRACT(YEAR FROM SENT_DATE) = 2022
GROUP BY SENDER_ID
ORDER BY MESSAGE_COUNT DESC
LIMIT 2

--EX6 
SELECT TWEET_ID FROM TWEETS
WHERE LENGTH(CONTENT) > 15

--EX7
--EX8
select COUNT(ID) AS NUMBER_EMPLOYEE
from employees
WHERE EXTRACT(MONTH FROM JOINING_DATE) BETWEEN 1 AND 7
AND EXTRACT(YEAR FROM JOINING_DATE) = 2022

--EX9
select FIRST_NAME,
POSITION('a' IN FIRST_NAME) AS POSITION_NAME
from worker
WHERE FIRST_NAME = 'Amitah';

--EX10
select SUBSTRING(title, LENGTH(winery)+2,4)
from winemag_p2
WHERE COUNTRY= 'Macedonia'





